### ISSUE TITLE
Could you please tell me why you set Unet part requires_grad = False

### ISSUE THREAD

**Issue by beihaiyou** [xianlin7/BATFormer#5]
Thanks for your remarkable work! but I have a question. You set Unet part requires_grad = False, but CGT and BLT part requires_grad = True, the Unet part doesn't load any pretrained checkpoints. Could you please tell me why? I wish your reply.
The result is good, that makes me more confused.

**Comment by xianlin7** [comment]
Actually, this line of code, i.e., "requires_grad = True/False" needs to be adjusted manually during training. As described in the implementation details, set "requires_grad = True" for the first 350 epochs, then load the best model and set "requires_grad = False" for the following 50 epochs.

As for setting "requires_grad = False" during the whole training procedure and obtaining a good result, it may be because CGT and BLT can perform well even on the randomly initialized Unet backbone.

**Comment by xianlin7** [comment]
> Thanks for your remarkable work! but I have a question. You set Unet part requires_grad = False, but CGT and BLT part requires_grad = True, the Unet part doesn't load any pretrained checkpoints. Could you please tell me why? I wish your reply. The result is good, that makes me more confused.

Thanks for your question, we have further stated details about this setting in the revised code.

**Comment by xianlin7** [comment]
> Thanks for your remarkable work! but I have a question. You set Unet part requires_grad = False, but CGT and BLT part requires_grad = True, the Unet part doesn't load any pretrained checkpoints. Could you please tell me why? I wish your reply. The result is good, that makes me more confused.

Actually, this line of code, i.e., "requires_grad = True/False" needs to be adjusted manually during training. As described in the implementation details, set "requires_grad = True" for the first 350 epochs, then load the best model and set "requires_grad = False" for the following 50 epochs.

As for setting "requires_grad = False" during the whole training procedure and obtaining a good result, it may be because CGT and BLT can perform well even on the randomly initialized Unet backbone.

**Comment by beihaiyou** [comment]
thanks so much for your reply!
